# Generated by Django 3.0.5 on 2020-04-09 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_fundraisers', '0003_auto_20200409_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundraiser',
            name='founder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fundraisers', to=settings.AUTH_USER_MODEL, verbose_name='founder'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fundraiser_members', to=settings.AUTH_USER_MODEL, verbose_name='member'),
        ),
    ]
