# Generated by Django 3.0.5 on 2020-04-08 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_fundraisers', '0002_auto_20200409_0417'),
        ('django_extra_referrals', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('reg_number', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Reg number')),
                ('inner_id', models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True, verbose_name='Inner ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('fullname', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('is_paid', models.BooleanField(default=False, editable=False)),
                ('is_cancelled', models.BooleanField(default=False, editable=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_donations.withdraw_set+', to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'Withdraw',
                'verbose_name_plural': 'Withdraws',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='donation',
            name='campaigner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donation_campaigns', to='django_extra_referrals.Referral'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='referral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donation_referrals', to='django_extra_referrals.Referral'),
        ),
        migrations.CreateModel(
            name='ReferralWithdraw',
            fields=[
                ('withdraw_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='donations.Withdraw')),
                ('account_balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_extra_referrals.Referral')),
            ],
            options={
                'verbose_name': 'Referral Withdraw',
                'verbose_name_plural': 'Referral Withdraws',
                'ordering': ['-created_at'],
            },
            bases=('donations.withdraw',),
        ),
        migrations.CreateModel(
            name='FundraiserWithdraw',
            fields=[
                ('withdraw_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='donations.Withdraw')),
                ('account_balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_fundraisers.Fundraiser')),
            ],
            options={
                'verbose_name': 'Fundraiser Withdraw',
                'verbose_name_plural': 'Fundraiser Withdraws',
                'ordering': ['-created_at'],
            },
            bases=('donations.withdraw',),
        ),
    ]
