# Generated by Django 3.0.5 on 2020-04-09 07:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_extra_referrals', '0002_auto_20200409_0542'),
        ('donations', '0003_auto_20200409_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='donation',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='donation',
            name='random',
            field=models.DecimalField(decimal_places=0, help_text='Used when tracing payment', max_digits=15, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Random'),
        ),
        migrations.AlterField(
            model_name='referralwithdraw',
            name='account_balance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdraws', to='django_extra_referrals.Referral'),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
