# Generated by Django 3.0.5 on 2020-04-09 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_fundraisers', '0002_auto_20200409_0417'),
        ('donations', '0004_auto_20200409_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundraiserwithdraw',
            name='account_balance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdraws', to='django_fundraisers.Fundraiser'),
        ),
    ]
