# Generated by Django 3.0.5 on 2020-04-09 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_auto_20200409_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fundraiserwithdraw',
            old_name='account_balance',
            new_name='fundraiser',
        ),
        migrations.RenameField(
            model_name='referralwithdraw',
            old_name='account_balance',
            new_name='referral',
        ),
    ]
