# Generated by Django 3.0.5 on 2020-04-11 10:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('django_cashflow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donations', '0006_auto_20200409_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='donations', to='django_cashflow.Cash', verbose_name='Payment Method'),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='withdraws', to='django_cashflow.Cash', verbose_name='Payment Method'),
        ),
        migrations.CreateModel(
            name='PaymentConfirmation',
            fields=[
                ('reg_number', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Reg number')),
                ('inner_id', models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True, verbose_name='Inner ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('name', models.CharField(help_text='Your name.', max_length=255, verbose_name='Name')),
                ('donation_number', models.CharField(blank=True, help_text='Nomor transaksi donasi', max_length=255, null=True, verbose_name='Donation Number')),
                ('transfer_receipt', models.ImageField(upload_to='', verbose_name='Transfer receipt')),
                ('account_name', models.CharField(help_text='Your bank account name.', max_length=255, verbose_name='Account Name')),
                ('account_number', models.CharField(help_text='Your bank account number.', max_length=255, verbose_name='Account Number')),
                ('bank_name', models.CharField(help_text='Your bank account number.', max_length=255, verbose_name='Bank name')),
                ('amount', models.DecimalField(decimal_places=0, default=10000, help_text='Donation amount to be sent', max_digits=15, validators=[django.core.validators.MinValueValidator(10000)], verbose_name='Amount')),
                ('note', models.TextField(blank=True, help_text='Need help? please tell us.', max_length=500, null=True, verbose_name='Note')),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Verified at')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmations', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('donation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='donations.Donation', verbose_name='Donation')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='confirmations', to='django_cashflow.Cash', verbose_name='Payment Method')),
            ],
            options={
                'verbose_name': 'Confirmation',
                'verbose_name_plural': 'Confirmations',
            },
        ),
    ]
