# Generated by Django 3.0.5 on 2020-04-11 11:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('django_cashflow', '0001_initial'),
        ('django_fundraisers', '0004_auto_20200409_2003'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donations', '0007_auto_20200411_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawRequest',
            fields=[
                ('reg_number', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Reg number')),
                ('inner_id', models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True, verbose_name='Inner ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('withdraw_account_name', models.CharField(help_text='Your payment account name.', max_length=255, verbose_name='Account Name')),
                ('withdraw_account_number', models.CharField(help_text='Your payment account number.', max_length=255, verbose_name='Account Number')),
                ('withdraw_provider_name', models.CharField(help_text='Your payment account number.', max_length=255, verbose_name='Bank name')),
                ('amount', models.DecimalField(decimal_places=0, default=10000, help_text='Donation amount to be sent', max_digits=15, validators=[django.core.validators.MinValueValidator(10000)], verbose_name='Amount')),
                ('note', models.TextField(blank=True, help_text='Need help? please tell us.', max_length=500, null=True, verbose_name='Note')),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Verified at')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdraw_requests', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('fundraiser', models.ForeignKey(blank=True, help_text='Choose if you want to withdraw your fundraiser account ', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='withdraw_requests', to='django_fundraisers.Fundraiser', verbose_name='Withdraw Request')),
                ('withdraw_method', models.ForeignKey(limit_choices_to={'checkout': True}, on_delete=django.db.models.deletion.PROTECT, related_name='withdraw_requests', to='django_cashflow.Cash', verbose_name='Payment Method')),
            ],
            options={
                'verbose_name': 'Withdraw Request',
                'verbose_name_plural': 'Withdraw Request',
            },
        ),
    ]
