# Generated by Django 3.0.5 on 2020-04-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0008_donation_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentconfirmation',
            name='donation_number',
            field=models.CharField(blank=True, help_text='Donation number.', max_length=255, null=True, verbose_name='Donation Number'),
        ),
    ]
