# Generated by Django 3.0.5 on 2020-04-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0010_auto_20200410_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentconfirmation',
            name='name',
            field=models.CharField(default='Jhon', help_text='Your name.', max_length=255, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentconfirmation',
            name='donation_number',
            field=models.CharField(blank=True, help_text='Nomor transaksi donasi', max_length=255, null=True, verbose_name='Donation Number'),
        ),
    ]
