# Generated by Django 3.0.5 on 2020-04-11 10:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('reg_number', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Reg number')),
                ('inner_id', models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True, verbose_name='Inner ID')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('checkin', models.BooleanField(default=True, verbose_name='Check In')),
                ('checkout', models.BooleanField(default=True, verbose_name='Check Out')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('balance', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15, verbose_name='Balance')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_django_cashflow.cash_set+', to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'Cash',
                'verbose_name_plural': 'Cashes',
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('cash_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_cashflow.Cash')),
                ('bank_name', models.CharField(max_length=150)),
                ('branch_office', models.CharField(blank=True, max_length=150, null=True)),
                ('account_name', models.CharField(max_length=150)),
                ('account_number', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Bank Account',
                'verbose_name_plural': 'Bank Accounts',
            },
            bases=('django_cashflow.cash',),
        ),
        migrations.CreateModel(
            name='CashAccount',
            fields=[
                ('cash_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_cashflow.Cash')),
            ],
            options={
                'verbose_name': 'Cash Account',
                'verbose_name_plural': 'Cash Accounts',
            },
            bases=('django_cashflow.cash',),
        ),
        migrations.CreateModel(
            name='Mutation',
            fields=[
                ('reg_number', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Reg number')),
                ('inner_id', models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True, verbose_name='Inner ID')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('object_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='reference id')),
                ('transfer_receipt', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Transfer receipt')),
                ('account_name', models.CharField(help_text='Account/holder name.', max_length=255, verbose_name='Account Name')),
                ('account_number', models.CharField(help_text='Account number/ID.', max_length=255, verbose_name='Account Number')),
                ('provider_name', models.CharField(help_text='Provider. (Bank Mandiri or Gopay)', max_length=255, verbose_name='Provider name')),
                ('flow', models.CharField(choices=[('IN', 'In'), ('OUT', 'Out')], default='IN', editable=False, max_length=3, verbose_name='Flow')),
                ('amount', models.DecimalField(decimal_places=0, default=10000, help_text='Donation amount to be sent', max_digits=15, validators=[django.core.validators.MinValueValidator(5000)], verbose_name='Amount')),
                ('old_balance', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15, verbose_name='Balance')),
                ('balance', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15, verbose_name='Balance')),
                ('note', models.TextField(blank=True, help_text='Need help? please tell us.', max_length=500, null=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Verified at')),
                ('cash_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mutations', to='django_cashflow.Cash', verbose_name='Cash Account')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType', verbose_name='reference type')),
                ('creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mutations', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
            ],
            options={
                'verbose_name': 'Mutation',
                'verbose_name_plural': 'Mutations',
                'ordering': ['-created_at'],
            },
        ),
    ]
