# Generated by Django 3.0.5 on 2020-04-07 12:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_cashflow', '0003_auto_20200407_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutation',
            name='amount',
            field=models.DecimalField(decimal_places=0, default=10000, help_text='Donation amount to be sent', max_digits=15, validators=[django.core.validators.MinValueValidator(5000)], verbose_name='Amount'),
        ),
    ]
