# Generated by Django 3.0.5 on 2020-04-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_numerators', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numerator',
            name='reset_mode',
            field=models.CharField(choices=[('YEAR', 'YEARLY'), ('MONTH', 'MONTHLY'), ('NEVER', 'FIXED')], default='YEAR', max_length=50, verbose_name='reset mode'),
        ),
    ]
